=== BackupTheBerlios/open-egov-svn/trunk/data/laws-and-regulations/oeg-act.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Open E-Government Document Type Definition: act

  Diese DTD definiert den Aufbau des XML-Formats zur VerÃ¶ffentlichung
  der aktuellen Bundesgesetze und Rechtsverordnungen unter www.open-egov.de

  $Id$
-->

<!ENTITY oegname "Open E-Government">
<!ENTITY oegwww "http://www.open-egov.de/">

<!ELEMENT document (properties+, texts+)>

<!ELEMENT properties (element*)>

<!ELEMENT element EMPTY>
<!ATTLIST element
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT texts (text*)>

<!ELEMENT text (#PCDATA | section* | div*)>
<!ATTLIST text
  no CDATA #REQUIRED
  from CDATA #REQUIRED
  to CDATA #IMPLIED
  outofforce (yes | no) "no"
  lang (de | en) #REQUIRED
  status (complete | partial | missing | scan | file | other) #REQUIRED
>

<!ELEMENT div (#PCDATA | section* | div*)>
<!ATTLIST div
  level CDATA #REQUIRED
  description CDATA #REQUIRED
  title CDATA #IMPLIED
>

<!ELEMENT section (#PCDATA | paragraph* | comment)*>
<!ATTLIST section
  no CDATA #REQUIRED
  title CDATA #IMPLIED
>

<!ELEMENT paragraph (#PCDATA | link | em | break | list | comment)*>
<!ATTLIST paragraph
  no CDATA #REQUIRED
  value CDATA ""
  title CDATA #IMPLIED
>

<!ELEMENT link (#PCDATA)*>
<!ATTLIST link
  value CDATA #IMPLIED
>

<!ELEMENT list (item)+>
<!ATTLIST list
  type (number | lower-letter) "number"
  prefix CDATA #IMPLIED ""
  postfix CDATA #IMPLIED ""
>

<!ELEMENT item (#PCDATA)+>
<!ATTLIST item
  value CDATA #IMPLIED
>

<!ELEMENT image EMPTY>
<!ATTLIST image
  src CDATA #REQUIRED
  title CDATA #IMPLIED
  alt CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
>

<!ELEMENT file EMPTY>
<!ATTLIST file
  src CDATA #REQUIRED
  title CDATA #IMPLIED
  preview CDATA #IMPLIED
  type CDATA #IMPLIED
>

<!-- TODO: edit, em -->

=== BackupTheBerlios/open-egov-svn/trunk/data/laws-and-regulations/DE/ST/Schiedsstellen- und Schlichtungsgesetz.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE document SYSTEM "http://www.open-egov.de/dtd/1.0/oeg-act.dtd">

<document>
  <properties>
    <element name="version"       value="$Id$" />
    <element name="type"          value="act" />                                    <!-- type of document/Dokumenttyp: Gesetz -->
    <element name="local.type"    value="Landesnorm Sachsen-Anhalt" />
    <element name="title"         value="Schiedsstellen- und Schlichtungsgesetz" /> <!-- name -->
    <element name="short"         value="SchStG" />                                 <!-- abbreviation / Amtliche Abkürzung -->
    <element name="reference"     value="" />
    <element name="level"         value="federal state" />
    <element name="scope"         value="DE-ST" />
    <element name="languages"     value="de" />
    <element name="date of issue" value="2001-06-22" />                             <!-- Ausfertigungsdatum -->
    <element name="from"          value="2001-07-01" />                             <!-- valid from / Gültig ab -->
    <element name="to"            value="" />                                       <!-- valid to / Gültig bis, nothing if in force -->
    <element name="last-check"    value="2013-03-14" />                             <!-- last checked for changes -->
    <element name="last-edit"     value="2013-03-18" />
    <element name="editors"       value="" />
  </properties>

  <texts>
    <text no="1" from="2001-07-01" outofforce="yes" lang="de" status="missing" dateofissue="2001-06-22" title="Schiedsstellen- und Schlichtungsgesetz" short="SchStG" published="GVBl. LSA 2001, S. 214" changesummary="">
	</text>

    <text no="2" from="2002-01-01?" outofforce="yes" lang="de" status="missing" dateofissue="2001-12-07" published="GVBl. LSA S. 540, 548" changesummary="§§ 24, 34 a, 41 und 50 geändert durch Art. 62">
	</text>

    <text no="3" from="2004-01-04?" outofforce="yes" lang="de" status="missing" dateofissue="2004-03-26" published="GVBl. LSA S. 234, 235" changesummary="§ 17 geändert durch Art. 11">
	</text>

    <text no="4" from="2005-12-15?" outofforce="yes" lang="de" status="missing" dateofissue="2005-12-08" published="GVBl. LSA S. 726" changesummary="§ 34 a geändert durch Art. 3">
	</text>

    <text no="5" from="2008-02-21?" outofforce="yes" lang="de" status="missing" dateofissue="2008-02-14" published="GVBl. LSA S. 58" changesummary="§ 51 geändert durch Art. 6">
	</text>

    <text no="6" from="2008-12-10?" outofforce="yes" lang="de" status="missing" dateofissue="2008-12-02" published="GVBl. LSA S. 400" changesummary="mehrfach geändert">
	</text>

    <text no="7" from="2010-01-23?" outofforce="yes" lang="de" status="missing" dateofissue="2009-12-15" published="GVBl. LSA S. 648, 681" changesummary="§§ 11 und 12 geändert durch Art. 2 Abs. 33">
	</text>

    <text no="8" from="2010-02-01?" outofforce="yes" lang="de" status="missing" dateofissue="2010-01-15" published="GVBl. LSA S. 8" changesummary="mehrfach geändert durch Art. 6">
	</text>

    <text no="9" from="2010-04-21" outofforce="no" lang="de" status="complete" dateofissue="2010-04-13" published="GVBl. LSA S. 192, 193" changesummary="§ 34a geändert durch Art. 7">
      <div level="1" description="Erster Abschnitt" title="Die Schiedsstelle">
        <section no="1" title="">
		  <paragraph value="1">Zur Durchführung des Schlichtungsverfahrens über streitige Rechtsangelegenheiten richtet jede Gemeinde eine oder mehrere Schiedsstellen ein und unterhält sie. Innerhalb eines Amtsgerichtsbezirkes können Gemeinden mit anderen Gemeinden eine gemeinsame Schiedsstelle einrichten. Der Bezirk einer Schiedsstelle soll in der Regel nicht mehr als 20000 Einwohner umfassen. Die Schiedsstelle führt in ihrer Bezeichnung einen Zusatz, der auf die Gemeinde, die Verbandsgemeinde, die Verwaltungsgemeinschaft oder auf den Schiedsstellenbezirk hinweist.</paragraph>
		  <paragraph value="2">Die Gemeinden erfüllen die ihnen nach diesem Gesetz obliegenden Aufgaben im eigenen Wirkungskreis.</paragraph>
	    </section>
        <section no="2" title="">
          <paragraph value="1">Die Aufgaben der Schiedsstellen werden in der Regel von einer Schiedsfrau oder einem Schiedsmann (Schiedsperson) wahrgenommen. Die Schiedsperson ist ehrenamtlich tätig.</paragraph>
          <paragraph value="2">Die Schiedsstelle kann abweichend von <link>Absatz 1</link> mit einer oder einem Vorsitzenden und bis zu zwei weiteren Schiedspersonen besetzt werden.</paragraph>
        </section>
        <section no="3" title="">
          <paragraph value="1">Die Schiedsperson muss nach ihrer Persönlichkeit und ihren Fähigkeiten für das Amt geeignet sein. Sie soll ihre Wohnung im Schiedsstellenbezirk haben.</paragraph>
          <paragraph value="2">In das Amt soll nicht berufen werden, wer bei Beginn der Amtsperiode noch nicht das 25. Lebensjahr vollendet hat.</paragraph>
          <paragraph value="3">Als Schiedsperson ist ausgeschlossen,<list type="number" prefix="" postfix="."><item value="1">wer infolge Richterspruchs die Fähigkeit zur Bekleidung öffentlicher Ämter nicht besitzt oder wegen einer vorsätzlichen Tat zu einer Freiheitsstrafe von mehr als sechs Monaten verurteilt worden ist,</item><item value="2">wer wegen einer Tat angeklagt ist, die den Verlust der Fähigkeit zur Bekleidung öffentlicher Ämter zur Folge haben kann,</item><item value="3">wer in Vermögensverfall geraten ist.</item></list></paragraph>
          <paragraph value="4">Die Gemeinde und die Leitung des Amtsgerichtes (<link>§ 5 Abs. 1</link>) können personenbezogene Daten der zu wählenden oder zu bestätigenden Personen erheben, soweit dies nach den <link value="§ 3 Abs. 1 bis 3 SchStG">Absätzen 1 bis 3</link> erforderlich ist.</paragraph>
        </section>
        <section no="4" title="">
          <paragraph value="1">Die Schiedsperson wird für eine Amtszeit von fünf Jahren gewählt.</paragraph>
          <paragraph value="2">Das Amt der Schiedsperson endet vorzeitig, wenn die Schiedsstelle aufgelöst wird.</paragraph>
        </section>
        <section no="5" title="">
          <paragraph value="1">Die gewählte Schiedsperson bedarf der Bestätigung durch die Direktorin oder den Direktor oder die Präsidentin oder den Präsidenten des Amtsgerichtes (Leitung des Amtsgerichtes), in dessen Bezirk die Schiedsstelle ihren Sitz hat.</paragraph>
          <paragraph value="2">Die Leitung des Amtsgerichtes prüft, ob bei der Wahl der Schiedsperson die gesetzlichen Voraussetzungen gemäß <link>§ 3 Abs. 1 Satz 1</link> und <link value="§ 3 Abs. 3">Abs. 3</link> beachtet worden sind.</paragraph>
          <paragraph value="3">Die Bestätigung der Schiedsperson ist der gewählten Person und der Gemeinde, Verbandsgemeinde oder dem gemeinsamen Verwaltungsamt schriftlich mitzuteilen.</paragraph>
          <paragraph value="4">Die Entscheidung, durch die die Bestätigung einer Schiedsperson versagt wird, ist zu begründen und der gewählten Person sowie der Gemeinde, Verbandsgemeinde oder dem gemeinsamen Verwaltungsamt schriftlich mitzuteilen.</paragraph>
        </section>
        <section no="6" title="">
          <paragraph value="1">Die Schiedsperson wird von der Leitung des Amtsgerichtes in ihr Amt berufen und verpflichtet, ihre Aufgaben gewissenhaft und unparteiisch zu erfüllen.</paragraph>
          <paragraph value="2">Die Amtszeit der Schiedsperson beginnt mit der Berufung in das Amt. Bis zu ihrem Amtsantritt bleibt die bisherige Schiedsperson tätig.</paragraph>
        </section>
        <section no="7" title="">
          <paragraph value="1">Die Berufung zur Schiedsperson kann eine gewählte Person ablehnen, die<list type="number" prefix="" postfix="."><item value="1">das 62. Lebensjahr vollendet hat,</item><item value="2">infolge Krankheit auf voraussichtlich längere Zeit gehindert ist, das Amt auszuüben,</item><item value="3">aus beruflichen Gründen häufig oder länger von ihrer Wohnung im Sinne von <link>§ 3 Abs. 1 Satz 2</link> abwesend ist,</item><item value="4">aus sonstigen wichtigen Gründen das Amt nicht ausüben kann.</item></list></paragraph>
          <paragraph value="2"><link>Absatz 1 Nr. 2 bis 4</link> gilt entsprechend für die Niederlegung des Amtes.</paragraph>
          <paragraph value="3">Über die Befugnis zur Ablehnung oder Niederlegung des Amtes entscheidet die Leitung des Amtsgerichtes.</paragraph>
        </section>
        <section no="8" title="">
          <paragraph value="1">Die Schiedsperson ist ihres Amtes zu entheben, wenn die Voraussetzungen für ihre Wahl nach <link>§ 3 Abs. 1</link> nicht mehr vorliegen oder nachträglich Umstände im Sinne des <link>§ 3 Abs. 1 Satz 1</link> oder <link value="§ 3 Abs. 3">Abs. 3</link> bekannt werden, die ihrer Wahl entgegengestanden hätten. Sie kann ferner aus wichtigem Grund ihres Amtes enthoben werden. Ein wichtiger Grund liegt insbesondere vor, wenn die Schiedsperson<list type="number" prefix="" postfix="."><item value="1">ihre Pflichten gröblich verletzt hat,</item><item value="2">sich als unwürdig erwiesen hat,</item><item value="3">ihr Amt nicht mehr ordnungsgemäß ausüben kann.</item></list></paragraph>
          <paragraph value="2">Über die Amtsenthebung entscheidet auf Antrag der Leitung des Amtsgerichtes nach Anhörung der Schiedsperson und der zuständigen Gemeinde, der zuständigen Verbandsgemeinde oder des zuständigen gemeinsamen Verwaltungsamtes die Präsidentin oder der Präsident des Landgerichtes.</paragraph>
        </section>
        <section no="9" title="">
